### PR TITLE
Top Bar

### PR DESCRIPTION
**Pull request by NSagan271**
The top bars for all of the pages except for the login page link to
pages that I thought were appropriate (Ones from this list: (Settings,
Create, Suggest, or Login) that could not be accessed directly from
that page ). The login page has a top bar that contains no links, only
a back arrow.

### CODE REVIEW

**Comment by mydogisjibe** [comment]
I like it. Might we make the entire settings activity into that one drop-down? It might make navigation easier. What does everyone else think?

**Comment by xeonjake** [comment]
sure

**Comment by mydogisjibe** [comment]
If its done by 3-31-15 (Tuesday) morning ill push it that afternoon since we don't have school.

**Comment by xeonjake** [comment]
perfect

**Comment by NSagan271** [comment]
Done.

**Pull request merged**
